var elements = document.getElementsByTagName('*');


// Declared here, defined at bottom of file
var tribeList = {
"A'aninin":"Gros Ventre",
"Aha Makhav":"Mojave",
"Aha Makhav":"Mohave",
"Albaamaha Tribe":"Alabama Tribe",
"Albaamaha Indian":"Alabama Indian",
"Albaamaha Nation":"Alabama Nation",
"Anishinaabe":"Ojibwa",
"Anishinaabe":"Ojibwe",
"Anishinaabe":"Chippewa",
"Apsáalooke People":"Crow People",
"Apsáalooke Tribe":"Crow Tribe",
"Assiniboine":"Nakota",
"Báxoǰe":"Ioway",
"Báxoǰe people":"Iowa People",
"Báxoǰe Tribe":"Iowa Tribe",
"Chahta Yakni":"Choctaw",
"Chalá·at people":"Hoh people",
"Chalá·at Tribe":"Hoh Tribe",
"Cheti":"Chetco",
"Chikasha":"Chickasaw",
"Dakhóta":"Dakota",
"Naabeehó Bináhásdzo":"Navajo Nation",
"Diné":"Navajo",
"Diné":"Navajo",
"Este Mvskokvlke":"Muscogee",
"Este Mvskokvlke Nation":"Creek Nation",
"Este Mvskokvlke people":"Creek people",
"Este Mvskokvlke Tribe":"Creek Tribe",
"Gayogohó:no’":"Cayuga",
"Haudenosaunee":"Oneida",
"Hinono'eino":"Arapaho",
"Hinono'eiteen":"Arapahoe",
"Hopituh Shi-nu-mu":"Hopi",
"Iháŋktȟuŋwaŋ":"Western Dakota",
"Isáŋyathi":"Eastern Dakota",
"Iswa":"Catawba",
"Kahosadi":"Shasta",
"Káínawa":"Kainai",
"Káínawa":"Blood Tribe",
"Kalth Tindé":"Plains Apache",
"Kalth Tindé Tribe of Oklahoma":"Apache Tribe of Oklahoma",
"Gnoozhekaaning":"Bay Mills Indian Community",
"Koasati":"Coushatta",
"Ktunaxa":"Kutenai",
"Ktunaxa":"Kootenay",
"Ktunaxa":"Kootenai",
"Kuupangaxwichem":"Cupeño",
"Kwapa":"Cocopah",
"Kwih-dich-chuh-ahtx":"Makah",
"Lakȟóta":"Lakota",
"Lenape People":"Delaware People",
"Lenape Tribe":"Delaware Tribe",
"Lenape Nation":"Delaware Nation",
"Liksiyu":"Cayuse",
"Mamaceqtaw":"Menominee",
"Myaamiaki":"Miami",
"Natinixwe":"Hupa",
"Natinixwe":"Hoopa",
"N'de":"Apache",
"N'de":"Apaches",
"Nēhiyaw Nation":"Cree Nation",
"Nēhiyaw Tribe":"Cree Tribe",
"Nēhiyaw People":"Cree People",
"Nēhiyaw Indian":"Cree Indian",
"Neshnabé":"Pottawatomi",
"nəxʷsƛ̕ay̕əm":"Klallam",
"nəxʷsƛ̕ay̕əm":"Clallam",
"Ni'ekeni":"Mattole",
"Ni'ekeni":"Bear River Indians",
"Nishnaabe":"Odawa",
"Nishnaabe":"Ottawa",
"Nishnaabe":"Odaawaa",
"Niúachi":"Missouria",
"Niúachi people":"Missouri people",
"Niúachi Tribe":"Missouri Tribe",
"Noxwsʼáʔaq":"Nooksack",
"Nümü Tümpisattsi":"Timbisha",
"Nʉmʉnʉʉ":"Comanche",
"Nüwüwü":"Chemehuevi",
"Nyyhmy Tribe":"Mono Tribe",
"Nyyhmy Nation":"Mono Nation",
"Nyyhmy people":"Mono people",
"Nyyhmy Indian":"Mono Indian",
"Očhéthi Šakówiŋ":"Sioux",
"Oglala":"Oglala Sioux",
"Olekwo'l":"Yurok",
"Onöñda’gaga’":"Onondaga",
"Payómkawichum":"Luiseño",
"Payómkawichum":"Luiseno",
"Piikáni":"Piegan",
"Piikáni":"Piegan Blackfeet",
"Piipaash":"Maricopa",
"P'squosa":"Wenatchi",
"Ql̓ispé":"Pend d’Oreilles",
"Ql̓ispé":"Kalispel",
"Qwû'lh-hwai-pûm":"Klickitat",
"Qwû'lh-hwai-pûm":"Klikitat",
"Schitsu'umsh":"Coeur d'Alene",
"Shaawana":"Shawnee",
"Siksikaitsitapi":"Blackfoot",
"Siksikaitsitapi":"Blackfeet",
"Siksikáwa":"Siksika Nation",
"Squalli-Absch":"Nisqually",
"Taa-laa-wa Dee-ni":"Tolowa",
"Taaqtam":"Serrano",
"the Apsáalooke":"the Crow",
"the Báxoǰe":"the Iowa",
"Chalá·at Tribe":"Hoh Tribe",
"Chalá·at people":"Hoh people",
"Chalá·at Nation":"Hoh Nation",
"Chalá·at Indian":"Hoh Indian",
"the Este Mvskokvlke":"the Creek",
"the Lenape":"the Delaware",
"Tsalagi":"Cherokee",
"Tsėhéstáno":"Northern Cheyenne Indian Reservations",
"Tsêhéstáno":"Cheyenne",
"Tsuut'ina":"Sarcee",
"Wacq!ó":"Wasco",
"Wacq!ó-Wishram":"Wasco-Wishram",
"Wánapam":"Wanapum",
"Wazhazhe":"Osage",
"Wolastoqiyik":"Maliseet",
"Xvsh":"Tolowa",
"Xwlemi":"Lummi",
"ʔívil̃uqaletem":"Cahuilla",
"Yoeme":"Yaqui",
"Nomlāqa":"Nomlaki",
"Chaticks si Chaticks":"Pawnee",
"Peskotomuhkati":"Passamaquoddy",
"Panawahpskek":"Penobscot",
"Peewaareewa":"Peoria",
"Meshkwahkihaki":"Meskwaki",
"Meshkwahkihaki":"Mesquakie",
"sqʷuqʷóbəš":"Skokomish",
"Aqokúlo":"Chimakum",
"Sduk-al-bixw":"Snoqualmie",
"Iháŋkthuŋwaŋna":"Pabakse",
"Sisíthuŋwaŋ":"Sisseton",
"Waȟpéthuŋwaŋ":"Wahpeton",
"Spoqe'ind":"Spokan",
"Spoqe'ind":"Spokane",
"Stoluck-wa-mish":"Stillaguamish",
"Akwesasne":"St. Regis Mohawk Reservation",
"Kanien'kehá:ka":"Mohawk Nation",
"Kanien'kehá:ka people":"Mohawk People",
"Kanien'kehá:ka Tribe":"Mohawk Tribe",
"Kanien'kehá:ka Indian":"Mohawk Indian",
"Meshkwahkihaki Tribe":"Fox Tribe",
"Meshkwahkihaki Nation":"Fox Nation",
"Meshkwahkihaki people":"Fox people",
"Meshkwahkihaki Indian":"Fox Indian",
"oθaakiiwaki Tribe":" Sac Tribe",
"oθaakiiwaki people":" Sac People",
"oθaakiiwaki Nation":" Sac Nation",
"oθaakiiwaki and Meshkwahkihaki":"Sac and Fox",
"oθaakiiwaki & Meshkwahkihaki":"Sac & Fox",
"oθaakiiwaki":"Sauk",
"Poarch Band of Mvskokvlke Indians":"Poarch Band of Creek Indians",
"Poarch Band of Mvskokvlke":"Poarch Band of Creeks",
"Nomlāqa Bōda":"Paskenta Band of Nomlaki Indians",
"Numakaki":"Mandan",
"Hiraacá":"Hidatsa",
"Numakaki":"Mandan",
"Waashiw":"Washoe",
"Tickanwa•tic":"Tonkawa",
"Sdoh-doh-hohbsh":"Snohomish",
"/sʔémǝš/":"Snohomish",
"Wendat":"Wyandotte",
"A:shiwi":"Zuni",
"Tanêks(a)":"Biloxi",
"Skarù:ręˀ":"Tuscarora",
"Niimíipuu":"Nez Perce"



}

for (var i = 0; i < elements.length; i++) {
    var element = elements[i];

    for (var j = 0; j < element.childNodes.length; j++) {
        var node = element.childNodes[j];

        if (node.nodeType === Node.TEXT_NODE) {
            var text = node.nodeValue;
            var replacedText = text;

            // Create regex search string of tribe names (keys) separated by pipe
            // g = matches all instances
            // i = case-insensitive
            var regexStr = new RegExp(Object.keys(tribeList).join("|"),"gi");
            replacedText = replacedText.replace(regexStr, function(matched) {
                return tribeList[matched];
            });

            // If any matches were found, replace in document
            if (replacedText !== text) {
                element.replaceChild(document.createTextNode(replacedText), node);
            }
			
			
        }
    }
}
